insert into item (id, title, body, priority , schedule_time, complete_time) values (1, 'Crooked Arrows', 'Distributed motivating project', false, '3/18/2023', '5/20/2021');
insert into item (id, title, body, priority , schedule_time, complete_time) values (2, 'Modern Times', 'Mandatory system-worthy solution', false, '1/6/2023', '5/30/2023');
insert into item (id, title, body, priority , schedule_time, complete_time) values (3, 'Fist of the North Star', 'Virtual zero tolerance groupware', true, '10/16/2023', '2/12/2022');
insert into item (id, title, body, priority , schedule_time, complete_time) values (4, 'Child, The', 'Cloned next generation array', true, '2/13/2023', '1/27/2022');
insert into item (id, title, body, priority , schedule_time, complete_time) values (5, 'Deliver Us from Eva', 'Multi-lateral secondary ability', false, '9/1/2022', '3/15/2023');
insert into item (id, title, body, priority , schedule_time, complete_time) values (6, 'Chill Out! (Descongélate!)', 'Robust demand-driven contingency', false, '7/27/2022', '11/19/2023');
insert into item (id, title, body, priority , schedule_time, complete_time) values (7, 'Diamond Arm, The (Brilliantovaya ruka)', 'Synergistic analyzing info-mediaries', false, '8/28/2023', '8/3/2021');
insert into item (id, title, body, priority , schedule_time, complete_time) values (8, 'Ninth Gate, The', 'Stand-alone object-oriented installation', false, '10/9/2023', '7/26/2021');
insert into item (id, title, body, priority , schedule_time, complete_time) values (9, 'Rainy Dog (Gokudô kuroshakai)', 'Fully-configurable 4th generation implementation', false, '8/10/2022', '1/16/2023');
insert into item (id, title, body, priority , schedule_time, complete_time) values (10, 'Burnt by the Sun (Utomlyonnye solntsem)', 'Polarised content-based policy', false, '11/25/2022', '5/15/2021');
insert into item (id, title, body, priority , schedule_time, complete_time) values (11, 'Dacii', 'Operative grid-enabled neural-net', false, '3/4/2023', '6/28/2021');
insert into item (id, title, body, priority , schedule_time, complete_time) values (12, 'Cover-Up', 'Self-enabling intermediate function', false, '9/25/2021', '3/3/2023');
insert into item (id, title, body, priority , schedule_time, complete_time) values (13, 'Godfather: Part II, The', 'Progressive foreground flexibility', false, '8/7/2022', '4/19/2023');
insert into item (id, title, body, priority , schedule_time, complete_time) values (14, 'Predator 2', 'Down-sized exuding flexibility', false, '8/28/2023', '1/14/2023');
insert into item (id, title, body, priority , schedule_time, complete_time) values (15, 'Dante''s Inferno: An Animated Epic', 'Innovative tertiary knowledge base', true, '12/22/2021', '12/13/2022');
insert into item (id, title, body, priority , schedule_time, complete_time) values (16, 'Another Gay Movie', 'Diverse methodical throughput', false, '1/18/2023', '11/14/2021');
insert into item (id, title, body, priority , schedule_time, complete_time) values (17, 'Love and Anarchy (Film d''amore e d''anarchia, ovvero ''stamattina alle 10 in via dei Fiori nella nota casa di tolleranza...'')', 'Synchronised motivating architecture', true, '1/1/2023', '7/16/2021');
insert into item (id, title, body, priority , schedule_time, complete_time) values (18, 'Regeneration', 'Synergized maximized policy', false, '6/11/2023', '3/6/2023');
insert into item (id, title, body, priority , schedule_time, complete_time) values (19, 'Robe, The', 'Cloned real-time methodology', true, '1/26/2023', '11/2/2023');
insert into item (id, title, body, priority , schedule_time, complete_time) values (20, 'Trick ''r Treat', 'Intuitive optimal array', false, '7/15/2022', '4/4/2022');
